#!/usr/bin/env bash
# Wraps an overlay in a generated kustomization with the values a deployment decides at run time, so committed files
# never carry them: deploy/k8s/overlays/.generated/<name>/kustomization.yaml (git-ignored).
#
# Usage: scripts/k8s-generate-overlay.sh <overlay> <name> [--namespace <namespace>] [--hostname <hostname>]
#   <overlay>   local, preview, or aks
#   <name>      the generated directory, for example production or pr-42
# Prints the generated directory. Set image tags on the overlay itself with `kustomize edit set image`.
set -euo pipefail

usage() {
  echo "usage: $0 <overlay> <name> [--namespace <namespace>] [--hostname <hostname>]" >&2
  exit 2
}

[[ $# -ge 2 ]] || usage
overlay="$1"
name="$2"
shift 2

namespace=""
hostname=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --namespace)
      [[ $# -ge 2 ]] || usage
      namespace="$2"
      shift 2
      ;;
    --hostname)
      [[ $# -ge 2 ]] || usage
      hostname="$2"
      shift 2
      ;;
    *) usage ;;
  esac
done

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

if [[ ! -f "deploy/k8s/overlays/$overlay/kustomization.yaml" ]]; then
  echo "No overlay named $overlay in deploy/k8s/overlays." >&2
  exit 1
fi

directory="deploy/k8s/overlays/.generated/$name"
mkdir -p "$directory"
{
  echo "# Generated by scripts/k8s-generate-overlay.sh. Not committed."
  echo "apiVersion: kustomize.config.k8s.io/v1beta1"
  echo "kind: Kustomization"
  if [[ -n "$namespace" ]]; then
    echo "namespace: $namespace"
  fi
  echo "resources:"
  echo "  - ../../$overlay"
  if [[ -n "$hostname" ]]; then
    echo "patches:"
    echo "  - target:"
    echo "      kind: HTTPRoute"
    echo "      name: flagforge"
    echo "    patch: |-"
    echo "      - op: add"
    echo "        path: /spec/hostnames"
    echo "        value: [\"$hostname\"]"
  fi
} > "$directory/kustomization.yaml"

echo "$directory"
